Update build_master_.yml

diff --git a/.github/workflows/build_master_.yml b/.github/workflows/build_master_.yml
--- a/.github/workflows/build_master_.yml
+++ b/.github/workflows/build_master_.yml
@@ -54,26 +54,26 @@ jobs:
         run: |
           cd
           curl -sL https://raw.githubusercontent.com/klever1988/nanopi-openwrt/zstd-bin/zstd | sudo tee /usr/bin/zstd > /dev/null
-          for i in {1..20}
-          do
-            if [[ "$DEVICE" != "r4s" ]] && [["$DEVICE" != "x86"]]; then
-              echo "Using ib: $DEVICE"
-              curl -sL --fail https://github.com/klever1988/sshactions/releases/download/cache/lede.$DEVICE.img.zst.0$i || break
-            else
-              curl -sL --fail https://github.com/aotsukiqx/nanopi-openwrt/releases/download/ib_cache/lede.$DEVICE.img.zst.0$i || break
-            fi
-          done | zstdmt -d -o lede.img || (truncate -s 40g lede.img && mkfs.btrfs -M lede.img)
-          LOOP_DEVICE=$(losetup -f) && echo "LOOP_DEVICE=$LOOP_DEVICE" >> $GITHUB_ENV
-          sudo losetup -P --direct-io $LOOP_DEVICE lede.img
-          mkdir lede && sudo mount -o nossd,compress=zstd $LOOP_DEVICE lede
-          BRANCH="master"
-          if [ -d 'lede/.git' ]; then
-          cd lede && rm -f zerospace && git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
-          git fetch && git reset --hard origin/$BRANCH
-          else
+          # for i in {1..20}
+          # do
+          #   if [[ "$DEVICE" != "r4s" ]] && [["$DEVICE" != "x86"]]; then
+          #     echo "Using ib: $DEVICE"
+          #     curl -sL --fail https://github.com/klever1988/sshactions/releases/download/cache/lede.$DEVICE.img.zst.0$i || break
+          #   else
+          #     curl -sL --fail https://github.com/aotsukiqx/nanopi-openwrt/releases/download/ib_cache/lede.$DEVICE.img.zst.0$i || break
+          #   fi
+          # done | zstdmt -d -o lede.img || (truncate -s 40g lede.img && mkfs.btrfs -M lede.img)
+          # LOOP_DEVICE=$(losetup -f) && echo "LOOP_DEVICE=$LOOP_DEVICE" >> $GITHUB_ENV
+          # sudo losetup -P --direct-io $LOOP_DEVICE lede.img
+          # mkdir lede && sudo mount -o nossd,compress=zstd $LOOP_DEVICE lede
+          # BRANCH="master"
+          # if [ -d 'lede/.git' ]; then
+          # cd lede && rm -f zerospace && git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
+          # git fetch && git reset --hard origin/$BRANCH
+          # else
           echo "Checkout imortalwrt and chown"
           sudo chown $USER:$(id -gn) lede && git clone -b $BRANCH --single-branch https://github.com/immortalwrt/immortalwrt lede
-          fi
+          # fi
 
       - name: Update feeds and packages
         run: |
