when finish upload remove img.zst and ib file

diff --git a/.github/workflows/buildmaster.yml b/.github/workflows/buildmaster.yml
--- a/.github/workflows/buildmaster.yml
+++ b/.github/workflows/buildmaster.yml
@@ -175,10 +175,10 @@ jobs:
       - name: Save cache state
         run: |
           cd
-          sleep 60
-          sudo mount -o remount,compress=no,nodatacow,nodatasum lede
-          cd lede/; pv /dev/zero > zerospace || true; sync; rm -f zerospace; cd -
-          sleep 60
+          # sleep 60
+          # sudo mount -o remount,compress=no,nodatacow,nodatasum lede
+          # cd lede/; pv /dev/zero > zerospace || true; sync; rm -f zerospace; cd -
+          # sleep 60
           sudo umount lede
           sudo losetup -d $LOOP_DEVICE
           export AUTH="Authorization: token ${{ secrets.SEC_TOKEN }}"
@@ -198,11 +198,12 @@ jobs:
           echo $ret | jq -r '.assets[] | select(.name == "ib-'$DEVICE'.tar.xz").id' | \
           xargs -n1 -i curl -X DELETE -H "$AUTH" "https://api.$cache_path/assets/{}"
           ls *img.zst* ib-$DEVICE.tar.xz | parallel --wc 'while true; do curl -T {} -H "$AUTH" -H "Content-Type: application/octet-stream" "https://uploads.$cache_path/$cache_repo_id/assets?name={}" && break || true; done'
-          set +e
-          for i in {1..20}; do curl -sL --fail https://github.com/aotsukiqx/nanopi-openwrt/releases/download/ib_cache/lede.$DEVICE.img.zst.0$i || break; done | zstdmt -d -o /dev/null
-          if [ $? -eq 0 ]; then break; fi
-          done
-          set -e
+          rm *img.zst* ib-$DEVICE.tar.xz
+          # set +e
+          # for i in {1..20}; do curl -sL --fail https://github.com/aotsukiqx/nanopi-openwrt/releases/download/ib_cache/lede.$DEVICE.img.zst.0$i || break; done | zstdmt -d -o /dev/null
+          # if [ $? -eq 0 ]; then break; fi
+          # done
+          # set -e
 
       - name: Send tg notification
         if: env.TG
